[toolchain]

[features]
seeds = true
skip-lint = false

[programs.devnet]
biometric_did_verifier = "BioDID1111111111111111111111111111111111111"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "npx ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
